name: Build Docker Image

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build --file Dockerfile --tag my-python-app:latest .
    
    - name: Tag Docker image
      run: docker tag my-python-app:latest rahulkumark72384/myapp:latest 

    # Add additional steps for testing your application if needed
