name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build --file Dockerfile --tag my-app:latest .

    - name: Tag Docker image
      run: docker tag my-app:latest rahulkumark72384/my-app:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.PASSWORD }}" | docker login --username ${{ secrets.USERNAME }} --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push rahulkumark72384/my-app:latest
